SELECT 'GANT SELECT ON "' + TABLE_SCHEMA + '"."' + TABLE_NAME + 
'" TO "QFA"' FROM information_schema.tables;


GRANT SELECT ON dbo.LOCATION TO QFA;
GRANT SELECT ON dbo.PROPERTY TO QFA;
GRANT SELECT ON dbo.STAFF_TYPE TO QFA;
GRANT SELECT ON dbo.CLIENT TO QFA;
GRANT SELECT ON dbo.PRODUCTION TO QFA;